---
- name: docker | Add docker repo
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

- name: docker | Add docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
    state: present

- name: docker | Install Docker
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose

- name: docker | adding existing user "{{ lookup('env','USER') }}" to group docker
  user:
    name: "{{ lookup('env','USER') }}"
    groups: docker
    append: true

- name: docker | install dependencies for docker-py
  apt:
    name: python3-pip
    state: present

- name: docker | install dependencies for docker_login
  pip:
    name: docker
    state: present

- name: docker | adding login/pass for dockerhub
  community.docker.docker_login:
    username: "{{ lookup('env','DOCKER_USER') }}"
    password: "{{ lookup('env','DOCKER_PASS') }}"
    email: "{{ lookup('env','DOCKER_MAIL') }}"
